Switch to CommonJS export for module: 'node16'
Kikobeats/is-url-http pull request #21
Opened 2023-01-31 20:29 UTC by karlhorky

As per https://github.com/Kikobeats/free-email-domains/pull/37#issuecomment-1410885100

2023-01-31 21:02 UTC, andrewbranch requested changes
I would also remove the `declare module` wrapper as you suggested, which means the `declare` modifier will move to before `function`.

2023-01-31 21:02 UTC, andrewbranch commented on index.d.ts
> +  export = function isUrlHttp(url: string): boolean;
For weird syntax reasons, it’s not quite inlinable like that
```suggestion
  function isUrlHttp(url: string): boolean;
  export = isUrlHttp;
```

2023-01-31 21:11 UTC, karlhorky commented
Done, removed the ambient declaration, thanks for the guidance!

2023-01-31 21:46 UTC, andrewbranch approved these changes

2023-02-01 09:27 UTC, Kikobeats commented
Thanks!

2023-02-01 09:32 UTC, merged

2023-02-01 09:33 UTC, karlhorky commented
Glad to help, thanks for the merge!